### PR TITLE
Update to 0.6.9

### PR DESCRIPTION
**Pull request by abergeron**
This goes with #https://github.com/conda-forge/libgpuarray-feedstock/pull/8

### CODE REVIEW

**Comment by abergeron** [comment]
Maybe I should have waited until the libgpuarray PR was merged before submitting this one, because the builds fail due the missing libgpuarray-0.6.9.

**Comment by abergeron** [comment]
How do we restart the CI for this?

**Comment by ocefpaf** [comment]
You have to navigate the CI web interface, it should be "intuitive." Let me know if you can find it or if I should re-start them for you.

**Comment by abergeron** [comment]
Ok.  I think I restarted all the builds.

**Pull request merged**
